backend/controllers/SysController.php
<?php

namespace backend\controllers;

use kartik\widgets\ActiveForm;
use Yii;
use backend\models\TMenu;
use yii\web\Response;

class SysController extends BackendController {
	/**
	 * 菜单管理
	 * 
	 * @return string
	 */
	public function actionMenu() {
		$list = TMenu::find ()->where ( 'level=1' )->all ();
		return $this->render ( 'index', [ 
				'list' => $list 
		] );
	}
	
	/**
	 * 添加新菜单
	 * 
	 * @return string|Response
	 */
	public function actionCreate() {
		$request = Yii::$app->request;
		$model = new TMenu ();
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
			Yii::$app->session->setFlash ( 'success' );
			return $this->redirect ( [ 
					'sys/menu' 
			] );
		} else {
			$model->loadDefaultValues ();
			$model->parentid = $request->get ( 'pid', 0 );
			$model->level = $request->get ( 'level', 0 ) + 1;
			return $this->render ( 'create', [ 
					'model' => $model,
					'plevel' => $request->get ( 'level', 0 ) 
			] );
		}
	}
	
	/**
	 * 更新菜单
	 * 
	 * @param
	 *        	$id
	 * @return string|Response
	 */
	public function actionUpdate($id) {
		$model = TMenu::findOne ( $id );
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
			Yii::$app->session->setFlash ( 'success' );
			return $this->redirect ( [ 
					'sys/menu' 
			] );
		} else {
			return $this->render ( 'update', [ 
					'model' => $model 
			] );
		}
	}
	
	/**
	 * 删除菜单
	 * 
	 * @return Response
	 * @throws \Exception
	 */
	public function actionMenudel() {
		$id = Yii::$app->request->get ( 'id' );
		$level = Yii::$app->request->get ( 'level' );
		// 循环删除是为了在afterDelete删除对应的permission
		// 一级菜单先删除孙子节点
		if ($level == 1) {
			$son = TMenu::find ()->where ( [ 
					'parentid' => $id,
					'level' => 2 
			] )->all ();
			foreach ( $son as $s ) {
				$gsons = TMenu::find ()->where ( [ 
						'parentid' => $s->id 
				] )->all ();
				foreach ( $gsons as $g ) {
					$g->delete ();
				}
			}
		}
		// 一二级菜单删除儿子节点
		if ($level <= 2) {
			$son = TMenu::find ()->where ( [ 
					'parentid' => $id 
			] )->all ();
			foreach ( $son as $s ) {
				$s->delete ();
			}
		}
		// 删除自身
		TMenu::findOne ( $id )->delete ();
		Yii::$app->session->setFlash ( 'success' );
		return $this->redirect ( [ 
				'sys/menu' 
		] );
	}
	
	/**
	 * Ajax 验证菜单名称
	 * 
	 * @return array
	 */
	public function actionAjaxvalidate() {
		if ($id = Yii::$app->request->post ( 'id' )) {
			$model = TMenu::findOne ( $id );
		} else {
			$model = new TMenu ();
		}
		if (Yii::$app->request->isAjax) {
			$model->load ( Yii::$app->request->post () );
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate ( $model, 'menuname' );
		}
	}
}

backend/views/sys/_form.php
<?php
/**
 *      ┏┓　　　┏┓
 *    ┏┛┻━━━┛┻┓
 *    ┃　　　　　　　┃
 *    ┃　　　━　　　┃
 *    ┃　┳┛　┗┳　┃
 *    ┃　　　　　　　┃
 *    ┃　　　┻　　　┃
 *    ┃　　　　　　　┃
 *    ┗━┓　　　┏━┛
 *        ┃　　　┃   神兽保佑
 *        ┃　　　┃   代码无BUG！
 *         ┃　　　┗━━━┓
 *        ┃　　　　　　　┣┓
 *        ┃　　　　　　　┏┛
 *        ┗┓┓┏━┳┓┏┛
 *          ┃┫┫　┃┫┫
 *          ┗┻┛　┗┻┛
 */
use yii\helpers\Html;

?>

<div class="col-lg-6">
    <?php $form = \kartik\widgets\ActiveForm::begin([
//        'action'        => '/sys/create',
        'validationUrl' => '/sys/ajaxvalidate',
    ]) ?>

    <?= $form->field($model, 'menuname')->textInput() ?>
    <?= $form->field($model, 'route', ['enableAjaxValidation' => true])->textInput()->hint('三级菜单必须要按照\'controller/action\'格式书写') ?>
    <?= $form->field($model, 'menuicon')->textInput()->hint('参照Bootstrap图标') ?>
    <?= $form->field($model, 'level')->dropDownList([
        '1' => '一级菜单',
        '2' => '二级菜单',
        '3' => '三级菜单',
    ], [
        'options' => [
            '1' => ['disabled' => ($plevel == 0) ? false : true],
            '2' => ['disabled' => ($plevel == 1) ? false : true],
            '3' => ['disabled' => ($plevel == 1 || $plevel == 2) ? false : true]
        ]
    ]) ?>
    <?= Html::activeHiddenInput($model, 'parentid') ?>
    <?= Html::hiddenInput('id', $model->id) ?>
    <div class="form-group center">
        <?= Html::submitButton($model->isNewRecord ? '添加' : '更新', ['class' => 'btn btn-lg btn-primary']) ?>
    </div>
    <?php $form->end() ?>
</div>

backend/views/sys/create.php
<?php
/**
 *      ┏┓　　　┏┓
 *    ┏┛┻━━━┛┻┓
 *    ┃　　　　　　　┃
 *    ┃　　　━　　　┃
 *    ┃　┳┛　┗┳　┃
 *    ┃　　　　　　　┃
 *    ┃　　　┻　　　┃
 *    ┃　　　　　　　┃
 *    ┗━┓　　　┏━┛
 *        ┃　　　┃   神兽保佑
 *        ┃　　　┃   代码无BUG！
 *         ┃　　　┗━━━┓
 *        ┃　　　　　　　┣┓
 *        ┃　　　　　　　┏┛
 *        ┗┓┓┏━┳┓┏┛
 *          ┃┫┫　┃┫┫
 *          ┗┻┛　┗┻┛
 */
/* @var $this yii\web\View */

$this->params['breadcrumbs'] = [
    [
        'label' => '路由管理',
        'url'   => \yii\helpers\Url::toRoute(['sys/menu'])
    ],
    '添加路由'
];
?>

<?= $this->render('_form', ['model' => $model, 'plevel' => $plevel]) ?>

backend/views/sys/index.php
<?php
/**
 * Created by PhpStorm.
 * User: olebar
 * Date: 2014/10/22
 * Time: 16:31:54
 */
use backend\assets\TreeAsset;
use yii\helpers\Url;

TreeAsset::register($this);


$this->params['breadcrumbs'] = [
    '菜单管理'
];
?>

<div class="tree">
    <ul>
        <li>
            <span><i class="icon-leaf"></i> <?= Yii::$app->params['webname'] ?></span> <a href=""></a>
            <a class="icon-plus" href="<?= Url::to(['sys/create','pid'=>0,'level'=>0]) ?>" title="添加"></a>
        </li>
        <li>
            <ul>
                <?php \yii\widgets\Pjax::begin([]) ?>
                <!--一级菜单-->
                <?php foreach ($list as $father): ?>
                    <li>
                        <span><i class="<?= $father->menuicon ?>"></i> <?= $father->menuname ?></span> <a href=""></a>
                        <a class="icon-plus" href="<?= Url::toRoute(['sys/create','pid'=>$father->id,'level'=>$father->level]) ?>" title="添加"></a>
                        <a class="icon-edit" href="<?= Url::toRoute(['sys/update','id'=>$father->id]) ?>"  title="编辑"></a>
                        <a class="icon-trash" href="<?= Url::toRoute(['sys/menudel','id'=>$father->id,'level'=>$father->level]) ?>" data-method="post"  data-confirm="确定要删除当前菜单以及所有子菜单吗?" title="删除"></a>

                        <ul>
                            <!--二级菜单-->
                            <?php foreach ($father->getSon()->all() as $son): ?>
                                <!--一级菜单下的3级菜单-->
                                <?php if ($son->level == 3): ?>
                                    <li>
                                        <span><i class="<?= $son->menuicon ?>"></i> <?= $son->menuname ?></span> <a href=""></a>
                                        <a class="icon-edit" href="<?= Url::toRoute(['sys/update','id'=>$son->id]) ?>" title="编辑"></a>
                                        <a class="icon-trash" href="<?= Url::toRoute(['sys/menudel','id'=>$son->id,'level'=>$son->level]) ?>" data-method="post"  data-confirm="确定删除当前菜单吗？" title="删除"></a>
                                    </li>
                                <?php else: ?>
                                    <li>
                                        <span><i class="icon-minus-sign"></i> <?= $son->menuname ?></span> <a
                                            href=""></a>
                                        <a class="icon-plus" href="<?= Url::toRoute(['sys/create','pid'=>$son->id,'level'=>$son->level]) ?>"  title="添加"></a>
                                        <!--<a class="icon-edit" href="javascript:;"
                                           onclick="add('edit',<?/*= $son->id; */?> , <?/*= $son->level */?>)" title="编辑"></a>-->
                                        <a class="icon-edit" href="<?= Url::toRoute(['sys/update','id'=>$son->id]) ?>" title="编辑"></a>
                                        <a class="icon-trash" href="<?= Url::toRoute(['sys/menudel','id'=>$son->id,'level'=>$son->level]) ?>" data-method="post"  data-confirm="确定删除当前菜单以及所有子菜单吗" title="删除"></a>
                                        <ul>
                                            <!--三级菜单-->
                                            <?php foreach ($son->getSon()->all() as $gson): ?>
                                                <li>
                                                    <span><i class="<?= $gson->menuicon ?>"></i> <?= $gson->menuname ?></span> <a
                                                        href=""></a>
                                                    <a class="icon-edit" href="<?= Url::toRoute(['sys/update','id'=>$gson->id]) ?>" title="编辑"></a>
                                                    <a class="icon-trash" href="<?= Url::toRoute(['sys/menudel','id'=>$gson->id,'level'=>$gson->level]) ?>" data-method="post"  data-confirm="确定删除吗?" title="删除"></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
            <?php \yii\widgets\Pjax::end() ?>
        </li>
    </ul>
</div>
<script>
    <?php $this->beginBlock('aa') ?>
    $('.tree li:has(ul)').addClass('parent_li').find(' > span');
    //默认收起
    //    $('.tree li.parent_li >span').parent('li.parent_li').find(' > ul > li').hide();
    $('.tree li.parent_li > span').on('click', function (e) {
        var children = $(this).parent('li.parent_li').find(' > ul > li');
        if (children.is(':visible')) {
            children.hide('fast');
            $(this).find(' > i').addClass('icon-plus-sign').removeClass('icon-minus-sign');
        } else {
            children.show('fast');
            $(this).find(' > i').addClass('icon-minus-sign').removeClass('icon-plus-sign');
        }
        e.stopPropagation();
    });
    <?php $this->endBlock(); ?>
</script>
<?php $this->registerJs($this->blocks['aa']) ?>

backend/views/sys/update.php
<?php
/**
 *      ┏┓　　　┏┓
 *    ┏┛┻━━━┛┻┓
 *    ┃　　　　　　　┃
 *    ┃　　　━　　　┃
 *    ┃　┳┛　┗┳　┃
 *    ┃　　　　　　　┃
 *    ┃　　　┻　　　┃
 *    ┃　　　　　　　┃
 *    ┗━┓　　　┏━┛
 *        ┃　　　┃   神兽保佑
 *        ┃　　　┃   代码无BUG！
 *         ┃　　　┗━━━┓
 *        ┃　　　　　　　┣┓
 *        ┃　　　　　　　┏┛
 *        ┗┓┓┏━┳┓┏┛
 *          ┃┫┫　┃┫┫
 *          ┗┻┛　┗┻┛
 */

/* @var $this yii\web\View */

$this->params['breadcrumbs'] = [
    [
        'label' => '路由管理',
        'url'   => \yii\helpers\Url::toRoute(['sys/menu'])
    ],
    '添加路由'
];
?>

<?= $this->render('_form', ['model' => $model, 'plevel' => '']) ?>